"""empty message

Revision ID: 20ab50782f05
Revises: bf654a8a40f3
Create Date: 2025-11-14 19:40:16.258723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20ab50782f05'
down_revision: Union[str, None] = 'bf654a8a40f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='用户主键，UUID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='登录邮箱，唯一'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='展示昵称'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='BCrypt 等方式加密后的密码'),
    sa.Column('bio', sa.Text(), nullable=True, comment='个人简介，可选'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='最近登录时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False, comment='项目 ID'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='项目拥有者用户 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述/简介'),
    sa.Column('language', sa.String(length=32), nullable=False, comment='主要语言，如 zh-CN/en-US'),
    sa.Column('target_platform', sa.String(length=64), nullable=False, comment='面向的发布平台'),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='project_status'), nullable=False, comment='项目状态'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='用户自定义标签数组'),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='额外元数据，可扩展字段'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_project_owner_name')
    )
    op.create_table('export_records',
    sa.Column('id', sa.UUID(), nullable=False, comment='导出记录 ID'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='关联项目'),
    sa.Column('format', sa.Enum('AE', 'PR', 'ZIP', name='export_format'), nullable=False, comment='导出格式'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='export_status'), nullable=False, comment='执行状态'),
    sa.Column('output_path', sa.String(length=512), nullable=True, comment='生成文件在存储中的路径'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='导出配置、版本信息等'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_records_project_id'), 'export_records', ['project_id'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.UUID(), nullable=False, comment='脚本版本 ID'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='所属项目 ID'),
    sa.Column('version', sa.Integer(), nullable=False, comment='脚本版本号，从 1 递增'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='脚本标题或章节名'),
    sa.Column('language', sa.Enum('ZH', 'EN', name='script_language'), nullable=False, comment='脚本使用的语言'),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='结构化脚本内容（场景、对白等）'),
    sa.Column('version_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='可选的全文快照，预留回滚用'),
    sa.Column('is_locked', sa.Boolean(), nullable=False, comment='是否锁定编辑，以防误改'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_script_project_version')
    )
    op.create_index(op.f('ix_scripts_project_id'), 'scripts', ['project_id'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.UUID(), nullable=False, comment='镜头 ID'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='所属项目'),
    sa.Column('script_id', sa.UUID(), nullable=True, comment='来源脚本版本，可为空'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='镜头顺序，从 1 开始'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='镜头标题'),
    sa.Column('description', sa.String(length=1024), nullable=False, comment='镜头描述/动作分解'),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='预计时长，秒'),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='shot_status'), nullable=False, comment='镜头当前状态'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='额外信息，如景别、镜头类型等'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sequence', name='uq_shot_project_sequence')
    )
    op.create_index(op.f('ix_shots_project_id'), 'shots', ['project_id'], unique=False)
    op.create_index(op.f('ix_shots_script_id'), 'shots', ['script_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False, comment='资产 ID'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='所属项目'),
    sa.Column('shot_id', sa.UUID(), nullable=True, comment='关联镜头，可为空'),
    sa.Column('type', sa.Enum('VIDEO', 'AUDIO', 'IMAGE', 'TEXT', 'SCRIPT', name='asset_type'), nullable=False, comment='资产类型'),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'NEEDS_REVISION', name='asset_status'), nullable=False, comment='当前状态'),
    sa.Column('storage_path', sa.String(length=512), nullable=False, comment='素材在本地挂载中的路径'),
    sa.Column('format', sa.String(length=32), nullable=True, comment='编码/格式，如 mp4/wav/png'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='时长，毫秒'),
    sa.Column('resolution', sa.String(length=32), nullable=True, comment='分辨率，如 1920x1080'),
    sa.Column('sample_rate', sa.Integer(), nullable=True, comment='音频采样率'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='生成参数、字幕等附加数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path', name='uq_asset_storage_path')
    )
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_shot_id'), 'assets', ['shot_id'], unique=False)
    op.create_table('synthesis_tasks',
    sa.Column('id', sa.UUID(), nullable=False, comment='任务 ID'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='所属项目'),
    sa.Column('shot_id', sa.UUID(), nullable=True, comment='关联镜头，可选'),
    sa.Column('voice_preset_id', sa.String(length=64), nullable=True, comment='使用的音色预设 ID'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='任务参数快照，方便重跑'),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='synthesis_task_status'), nullable=False, comment='任务状态'),
    sa.Column('result_path', sa.String(length=512), nullable=True, comment='生成文件在本地的路径'),
    sa.Column('error_message', sa.String(length=512), nullable=True, comment='失败原因，最多 512 字符'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='运行日志、用时等信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synthesis_tasks_project_id'), 'synthesis_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_synthesis_tasks_shot_id'), 'synthesis_tasks', ['shot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_synthesis_tasks_shot_id'), table_name='synthesis_tasks')
    op.drop_index(op.f('ix_synthesis_tasks_project_id'), table_name='synthesis_tasks')
    op.drop_table('synthesis_tasks')
    op.drop_index(op.f('ix_assets_shot_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_shots_script_id'), table_name='shots')
    op.drop_index(op.f('ix_shots_project_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_scripts_project_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_export_records_project_id'), table_name='export_records')
    op.drop_table('export_records')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
